### ISSUE TITLE
I can't enter the world, the client shows "can't connect to the world", the server shows a timeout and error

### ISSUE THREAD

**Issue by Nexvrek** [KCodeYT/VanillaGenerator#9]
2022-06-18 20:59:07.344 [Network Listener - #6] ERROR - Could not connect to background server! Address: Minecraft/127.0.1.1:50778
java.util.concurrent.CompletionException: java.util.concurrent.TimeoutException
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:332) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:347) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:636) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162) ~[?:?]
	at com.nukkitx.network.raknet.RakNetClient.onTick(RakNetClient.java:121) ~[powernukkitx-1.6.0.0-PNX-SNAPSHOT-shaded.jar:?]
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98) [powernukkitx-1.6.0.0-PNX-SNAPSHOT-shaded.jar:?]
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:176) [powernukkitx-1.6.0.0-PNX-SNAPSHOT-shaded.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) [powernukkitx-1.6.0.0-PNX-SNAPSHOT-shaded.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469) [powernukkitx-1.6.0.0-PNX-SNAPSHOT-shaded.jar:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503) [powernukkitx-1.6.0.0-PNX-SNAPSHOT-shaded.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) [powernukkitx-1.6.0.0-PNX-SNAPSHOT-shaded.jar:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [powernukkitx-1.6.0.0-PNX-SNAPSHOT-shaded.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.util.concurrent.TimeoutException
	... 9 more

**Comment by Nexvrek** [comment]
2022-06-18 21:03:10.385 [main] INFO  - §b§f[/192.168.0.5:10253] Logout，Reason：Timed out
2022-06-18 21:05:55.531 [main] INFO  - §b§f[/192.168.0.5:42047] Logout，Reason：Timed out
2022-06-18 21:06:34.981 [main] INFO  - §b§f[/192.168.0.5:42047] Logout戏，Reason：Timed out

**Comment by KCodeYT** [comment]
Have you made sure you have root permissions on the server you are running this plugin? You need those permissions so the powernukkitx server can start the background servers.

**Comment by Nexvrek** [comment]
> Have you made sure you have root permissions on the server you are running this plugin? You need those permissions so the powernukkitx server can start the background servers.

I used the "sudo" command to run powernukkitx, maybe I need to copy the original powernukkitx to a new folder and try again?

**Comment by KCodeYT** [comment]
You need to run the start command of powernukkitx as an administrative / root user.

**Comment by Nexvrek** [comment]
> You need to run the start command of powernukkitx as an administrative / root user.

I tried to run powernukkitx with the root command and enabled the plugin, but I still get the same error.

**Comment by MonoAdrian23** [comment]
And why is this a Plugin Issue?
WaterdogPe isnt compatible with PNX.

**Comment by ghitori** [comment]
> You need to run the start command of powernukkitx as an administrative / root user.

I had the same problem on my Windows, but during my test, I found the real reason is the plugin get the **`Wrong IP`** then couldn't connect with bds, rather than **` need Administrator/root`**, and then I solved it with disable my other network adapter. 
I guess that SYREB's problem is the plugin get the IP **`127.0.1.1`** but not **`127.0.0.1`**. And I prefer that the author could add a config to point the IP to resolve it.

**Comment by KCodeYT** [comment]
> > You need to run the start command of powernukkitx as an administrative / root user.
> 
> I had the same problem on my Windows, but during my test, I found the real reason is the plugin get the **`Wrong IP`** then couldn't connect with bds, rather than **` need Administrator/root`**, and then I solved it with disable my other network adapter. I guess that SYREB's problem is the plugin get the IP **`127.0.1.1`** but not **`127.0.0.1`**. And I prefer that the author could add a config to point the IP to resolve it.

Oh okay, im going to implement that to the config file, thanks for the information!

**Comment by Nexvrek** [comment]
> And why is this a Plugin Issue? WaterdogPe isnt compatible with PNX.

I don't think it has anything to do with plugin compatibility.
